import imageOne from "../assets/image_1.svg"
import imageTwo from "../assets/image_2.svg"
import imageThree from "../assets/image_3.svg"
import imageFour from "../assets/image_4.svg"

export const dataList = [
  {
    id: 1,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 2,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 3,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 4,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 5,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 6,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 7,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 8,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 9,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 10,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 11,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 12,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 13,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 14,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 15,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 16,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 17,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 18,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 19,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 20,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 21,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 22,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 23,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 24,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 25,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 26,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 27,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 28,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 29,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 30,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 31,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 32,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 33,
    name: "Apple iPhone 11 Pro Maxi",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageOne,
    amount: 90.85,
    discount: "124,00 TL",
    status: false,
  },
  {
    id: 34,
    name: "Apple iPhone 11",
    color: "Siyah",
    modelName: "Apple",
    imageUrl: imageTwo,
    amount: 90.85,
    discount: "900,00 TL",
    isBasket: false,
  },
  {
    id: 35,
    name: "iPhone 11 Kırmızı Kılıf",
    color: "Kırmızı",
    modelName: "Apple",
    imageUrl: imageThree,
    amount: 127.85,
    discount: "124,00 TL",
    isBasket: false,
  },
  {
    id: 36,
    name: "Apple Telefon",
    color: "Sarı",
    modelName: "Apple",
    imageUrl: imageFour,
    amount: 155.85,
    discount: "124,00 TL",
    isBasket: false,
  },
]

export default dataList
